# Github workflow for CI
# This code is part of $name_kebab_case$ project.

name: deploy
on:
  push:
    branches:
      - main
      - master
  # schedule:
  #   - cron: '0 0 * * *' # Everyday at 12am
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      API_BASE_URL: $\{{ secrets.API_BASE_URL }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup node env 🏗
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 20.1.0
          check-latest: true

      - run: npm install
      - run: npm run build

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: $\{{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p $\{{ secrets.SSH_PORT}} -H $\{{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzrhcP --chown=$\{{ secrets.SSH_USERNAME }}:$\{{ secrets.SSH_USERNAME }}
          path: ./build/
          remote_path: /home/www/$name_kebab_case$
          remote_host: $\{{ secrets.SSH_HOST }}
          remote_port: $\{{ secrets.SSH_PORT }}
          remote_user: $\{{ secrets.SSH_USERNAME }}
          remote_key: $\{{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync node_modules
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzrhcP --chown=$\{{ secrets.SSH_USERNAME }}:$\{{ secrets.SSH_USERNAME }} --delete-after
          path: ./node_modules
          remote_path: /home/www/$name_kebab_case$/
          remote_host: $\{{ secrets.SSH_HOST }}
          remote_port: $\{{ secrets.SSH_PORT }}
          remote_user: $\{{ secrets.SSH_USERNAME }}
          remote_key: $\{{ secrets.SSH_PRIVATE_KEY }}

      - name: Restart Node Server
        uses: appleboy/ssh-action@master
        with:
          host: $\{{ secrets.SSH_HOST }}
          username: $\{{ secrets.SSH_USERNAME }}
          key: $\{{ secrets.SSH_PRIVATE_KEY }}
          port: $\{{ secrets.SSH_PORT }}
          script: |
            pm2 restart $name_kebab_case$

